### ISSUE TITLE
error Constructor parameter should be str

### ISSUE THREAD

**Issue by IcyAlmond** [Akegarasu/fast-pixiv-proxy#3]
```
INFO:     127.0.0.1:45308 - "GET /92269291 HTTP/1.0" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/pixiv/fast-pixiv-proxy/fast-pixiv-proxy/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/pixiv/fast-pixiv-proxy/fast-pixiv-proxy/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/pixiv/fast-pixiv-proxy/fast-pixiv-proxy/venv/lib/python3.8/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/home/pixiv/fast-pixiv-proxy/fast-pixiv-proxy/venv/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/pixiv/fast-pixiv-proxy/fast-pixiv-proxy/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/pixiv/fast-pixiv-proxy/fast-pixiv-proxy/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/pixiv/fast-pixiv-proxy/fast-pixiv-proxy/venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/pixiv/fast-pixiv-proxy/fast-pixiv-proxy/venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/pixiv/fast-pixiv-proxy/fast-pixiv-proxy/venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/pixiv/fast-pixiv-proxy/fast-pixiv-proxy/venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/pixiv/fast-pixiv-proxy/fast-pixiv-proxy/venv/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/pixiv/fast-pixiv-proxy/fast-pixiv-proxy/venv/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/pixiv/fast-pixiv-proxy/fast-pixiv-proxy/venv/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/pixiv/fast-pixiv-proxy/fast-pixiv-proxy/venv/lib/python3.8/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/home/pixiv/fast-pixiv-proxy/fast-pixiv-proxy/venv/lib/python3.8/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/pixiv/fast-pixiv-proxy/fast-pixiv-proxy/main.py", line 31, in read_root
    resp = await get_pixiv(query=pixiv_path, img_type=img_type)
  File "/home/pixiv/fast-pixiv-proxy/fast-pixiv-proxy/pixiv.py", line 53, in get_pixiv
    return await reverse_pixiv(img_url)
  File "/home/pixiv/fast-pixiv-proxy/fast-pixiv-proxy/pixiv.py", line 72, in reverse_pixiv
    async with c.get(path, headers=p_headers, proxy=proxy) as rep:
  File "/home/pixiv/fast-pixiv-proxy/fast-pixiv-proxy/venv/lib/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/home/pixiv/fast-pixiv-proxy/fast-pixiv-proxy/venv/lib/python3.8/site-packages/aiohttp/client.py", line 423, in _request
    url = self._build_url(str_or_url)
  File "/home/pixiv/fast-pixiv-proxy/fast-pixiv-proxy/venv/lib/python3.8/site-packages/aiohttp/client.py", line 357, in _build_url
    url = URL(str_or_url)
  File "/home/pixiv/fast-pixiv-proxy/fast-pixiv-proxy/venv/lib/python3.8/site-packages/yarl/_url.py", line 154, in __new__
    raise TypeError("Constructor parameter should be str")
TypeError: Constructor parameter should be str
```

**Comment by IcyAlmond** [comment]
nvm the one in the readme doesn't exist on the actual pixiv site either
